name: Win_Tests

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.11.5]
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/cache@v3
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - uses: actions/cache@v3
      name: Install Cache
      with:
        path: ./.downloads
        key: install-${{ hashFiles('.downloads') }}
        restore-keys: install-

    - name: Set utf-8 Encoding
      run: |
        setx PYTHONIOENCODING "utf-8" && setx PYTHONLEGACYWINDOWSSTDIO "utf-8"

    - name: where git
      run: where git

    - name: Install dependencies
      run: |
        pip install -e '.[test]'

    - name: where git
      run: where git

    - name: Pre Run Environment state
      run: python test_install/prerun.py

    - name: install java
      run: pyflutterinstall --only-java -y

    - name: Where Java?
      run: setenvironment refresh "where java"

#    - name: Test java is 20
#      run: python test_install/is_java_version.py 20

    - name: install android
      run: python -m pyflutterinstall.install.android_sdk

    - name: install ant
      run: python -m pyflutterinstall.install.ant_sdk

    - name: install gradle
      run: python -m pyflutterinstall.install.gradle

    - name: install flutter
      run: python -m pyflutterinstall.install.flutter_sdk

    - name: post install check
      run: python -m pyflutterinstall.postrun

    - name: Print Flutter SDK Folder
      run: python test_install/print_flutter_folder.py
